### ISSUE TITLE
Does not work after the new update 

### ISSUE THREAD

**Issue by munkacsyb** [botcscriptcheck/botcscriptcheck.github.io#6]
No matter the script, this is the output I get: 

    Less than 13 Townsfolk characters
    No sources of droison
    No Outsider count modification
    No hidden Outsiders or reason for the Outsiders to hide
    No reason to distrust night deaths
    No evil-aligned droison characters

**Comment by botcscriptcheck** [comment]
This should be fixed now! Let me know if you encounter any issues!
